Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "copyright", "credits" or "license()" for more information.
>>> 
================== RESTART: /home/cs2017a206/jaisurya/3.py ==================
enter the marks40
grade B
grade c
Traceback (most recent call last):
  File "/home/cs2017a206/jaisurya/3.py", line 11, in <module>
    (fail)
NameError: name 'fail' is not defined
>>> 
================== RESTART: /home/cs2017a206/jaisurya/3.py ==================
enter the marks30
grade B
grade c
grade D
>>> 
================== RESTART: /home/cs2017a206/jaisurya/3.py ==================
enter the marks
================== RESTART: /home/cs2017a206/jaisurya/4.py ==================

================== RESTART: /home/cs2017a206/jaisurya/4.py ==================
>>> 
>>> 
================ RESTART: /home/cs2017a206/jaisurya/Random.py ================
3
>>> 5
5
>>> 
================ RESTART: /home/cs2017a206/jaisurya/Random.py ================
6
>>> 
================ RESTART: /home/cs2017a206/jaisurya/Random.py ================
1
>>> 
================ RESTART: /home/cs2017a206/jaisurya/Random.py ================
3
>>> 
================ RESTART: /home/cs2017a206/jaisurya/Random.py ================
5
>>> 
